# Generated by Django 3.0.2 on 2020-01-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=200)),
                ('filere', models.CharField(max_length=200)),
                ('nom_document', models.CharField(max_length=200)),
                ('niveau_etude', models.CharField(max_length=200)),
                ('date_document', models.DateField(verbose_name='date published')),
                ('description_document', models.CharField(max_length=200)),
                ('notation_document', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_topic', models.CharField(max_length=200)),
                ('titre_categorie', models.CharField(max_length=200)),
                ('titre_post', models.CharField(max_length=200)),
                ('text_post', models.CharField(max_length=200)),
                ('time_post', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
